#!/usr/bin/env python3

import re
from pathlib import Path

SOURCE = Path("tools/data/pinyin_simp.txt")
PINYIN = re.compile(r"[a-z]+")


def main() -> None:
    print("# Generated by tools/build_pinyin_reverse.py. DO NOT EDIT.")
    print("---")
    print("name: mohu_pinyin")
    print('version: "20260815"')
    print("sort: by_weight")
    print("use_preset_vocabulary: false")
    print("...")
    print()
    for raw_line in SOURCE.read_text(encoding="utf-8").splitlines():
        fields = raw_line.split("\t")
        if len(fields) < 3:
            continue
        text, pinyin, weight = fields[:3]
        if len(text) == 1 and PINYIN.fullmatch(pinyin):
            print(f"{text}\t{pinyin}\t{weight}")


if __name__ == "__main__":
    main()
